---
- name: Установить и настроить Prometheus и node_exporter
  hosts: ALT:REDOS
  become: true
  tasks:
    - name: Update ALT
      apt:
        update_cache: true
        state: latest
      when: ansible_os_family == "Astra Linux (Orel)"

    - name: Update REDOS
      yum:
        update_cache: true
        state: latest
      when: ansible_os_family == "RedHat"
      
    # Установка пакетов для RedHat-подобных систем
    - name: Установить пакеты для ALT
      package:
        name: "{{ item }}"
        state: present
      loop:
      - prometheus
      - prometheus-node_exporter
      - prometheus-alertmanager
      when: ansible_os_family == "Astra Linux (Orel)"


    - name: Установить пакеты для REDOS
      package:
        name: prometheus-node_exporter
        state: present
      when: ansible_os_family == "REDOS"
      
  
    # Настройка автозапуска и запуск node_exporter
    - name: Включить автозапуск и запустить node_exporter
      service:
        name: node_exporter
        enabled: true
        state: started

    # Перезапуск службы Prometheus
    - name: Перезапустить службу Prometheus
      service:
        name: prometheus
        state: restarted
        enabled: yes
