---
- name: Установить и настроить Prometheus и node_exporter
  hosts: ALT:REDOS
  become: true
  tasks:
    - name: Update ALT
      apt:
        name: '*'
        update_cache: true
        state: latest
      when: ansible_os_family == "Astra Linux (Orel)"

    - name: Update REDOS
      yum:
        name: '*'
        update_cache: true
        state: latest
      when: ansible_os_family == "REDOS"
      
    - name: Установить пакеты для ALT
      package:
        name: "{{ item }}"
        state: present
      loop:
      - prometheus
      - prometheus-node_exporter
      - prometheus-alertmanager
      when: ansible_os_family == "Astra Linux (Orel)"
      
    - name: Включить автозапуск и запустить node_exporter
      service:
        name: prometheus-node_exporter
        enabled: true
        state: started
      when: ansible_os_family == "REDOS"

    - name: Перезапустить службу Prometheus
      service:
        name: prometheus
        state: restarted
        enabled: yes
