---
- name: Установить и настроить Prometheus и node_exporter
  hosts: ALT:REDOS
  become: true
  tasks:



    # Установка пакетов для RedHat-подобных систем
    - name: Установить пакеты для RedHat
      package:
        name: "{{ item }}"
        state: present
      loop:
      - *
      - prometheus
      - prometheus-node_exporter
      - prometheus-alertmanager
      
  
    # Настройка автозапуска и запуск node_exporter
    - name: Включить автозапуск и запустить node_exporter
      service:
        name: node_exporter
        enabled: true
        state: started

    # Перезапуск службы Prometheus
    - name: Перезапустить службу Prometheus
      service:
        name: prometheus
        state: restarted
        enabled: yes