---
- name: Configure DHCP
  hosts: REDOS
  become: yes
  tasks:
    - name: Install dhcp server
      yum:
        name: dhcp-server
        state: present
        update_cache: yes

    - name: General Address
      set_fact:
        total_addresses: "{{ '10.0.0.0/24' | ipaddr('size') }}"

    - name: Solve Address
      set_fact:
        first_address: "{{ '10.0.0.0/24' | nthhost(total_addresses|int // 2 + 1) }}"
        last_address: "{{ '10.0.0.0/24' | nthhost(-5) }}"
    
    - name: Configure dhcp server
      copy:
        content: |
          subnet 10.0.0.0 netmask 255.255.255.0 {
            default-lease-time 600;
            max-lease-time 7200;
            option subnet-mask 255.255.255.0;
            option broadcast-address 10.0.0.255;
            option routers 172.21.10.60;
            option domain-name-servers 10.0.0.10;
            option domain-name "pro.hmao";
            option ntp-servers 172.21.10.60;
            range {{ first_address }} {{ last_address }};
          }
        dest: /etc/dhcp/dhcpd.conf

    - name: Restart DHCP
      service:
        name: dhcpd
        state: restarted