---
- hosts: Servers
  become: yes
  vars:
    dns_zones:
      - name: pro.hmao
        type: slave
        masters:
          - 172.21.10.60
  tasks:
    - name: Install bind9 Astra
      apt:
        name: bind9
        state: present
        update_cache: yes
      when: ansible_os_family == "Astra Linux (Orel)"

    - name: Install bind9 Alt
      apt_rpm:
        name: bind
        state: present
        update_cache: yes
      when: ansible_os_family == "Altlinux"

    - name: Install bind9 Redos
      yum:
        name: bind
        state: present
        update_cache: yes
      when: ansible_os_family == "REDOS"

    - name: Config bind9
      blockinfile:
        path: /etc/bind/named.conf.local
        block: |
          zone "{{ item.name }}" {
            type {{ item.type }};
            file "/var/lib/bind/db.{{ item.name }}";
            masters { {{ item.masters | join('; ') }}; };
            };
      loop: "{{ dns_zones }}"
      when: ansible_os_family == "Astra Linux (Orel)"

    - name: Config bind9
      blockinfile:
        path: /etc/named.conf
        block: |
          zone "{{ item.name }}" {
            type {{ item.type }};
            file "/var/named/slaves/db.{{ item.name }}";
            masters { {{ item.masters | join('; ') }}; };
            };
      loop: "{{ dns_zones }}"
      when: ansible_os_family == "REDOS"

    - name: Config bind9
      blockinfile:
        path: /etc/named.conf
        block: |
          zone "{{ item.name }}" {
            type {{ item.type }};
            file "/var/lib/bind/zone/slave/db.{{ item.name }}";
            masters { {{ item.masters | join('; ') }}; };
            };
      loop: "{{ dns_zones }}"
      when: ansible_os_family == "Altlinux"

    - name: Add DNS-address
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 127.0.0.1'
        state: present

    - name: Restart ssh/sshd
      service:
        name: bind
        state: restarted
      when: ansible_os_family == "Altlinux"

    - name: Restart ssh/sshd
      service:
        name: bind9
        state: restarted
      when: ansible_os_family == "Astra Linux (Orel)"

    - name: Restart ssh/sshd
      service:
        name: named
        state: restarted
      when: ansible_os_family == "REDOS"